### ISSUE TITLE
How to add knobs?

### ISSUE THREAD

**Issue by Alfrex92** [gojutin/gatsby-starter-typescript-deluxe#2]
Hi thanks for creating this repo, I have a question how can I add knobs?

I usually to this when using storybook, but the code below doesn't work:
```
import React from 'react'
import Component from '.'
import { withKnobs, number, text, boolean } from '@storybook/addon-knobs'

export default {
  title: 'atoms|Component',
  component: Component,
  decorators: [withKnobs]
}

export const Summary = () =>  (
  <Component
    // text={text('Message', 'Hello')}
  />
)
```

So, if I use the same format that you're using in the repo I can't see the knobs ("text")

```
import React from "react"
import { storiesOf } from "@storybook/react"
import { withKnobs, text } from "@storybook/addon-knobs"

import { withInfo } from "@storybook/addon-info"

import MemberInfo from "./index"

const story = storiesOf("Components|MemberInfo", module)
  .addDecorator(withInfo)
  .addDecorator(withKnobs)
story.add("Component", () => (
  <MemberInfo
    description={text("Description", "Lorem Ipsum")}
  />
))
```

Any idea of how can I display knobs?

**Comment by gojutin** [comment]
Hi, I just committed some new changes to this repo where you can find a working implementation of the `knobs` add-on with a button component. This should hopefully be enough to get you going. Good luck!

**Comment by gojutin** [comment]
Closing this issue. Please see previous comment and best of luck!

**Comment by Alfrex92** [comment]
Thanks for answering. I checked the last commits and it seems that you only update the dependencies and some linting rules. Is there something that I need to add to the code to make knobs work? Thanks

**Comment by gojutin** [comment]
No problem! I had a working implementation of the knobs add-on (button component) prior to this last commit. You should be able to follow what I did on that one to get yours working.

**Comment by Alfrex92** [comment]
I can't make it work 😢, I've stuck for days. Any idea why is not working?
https://github.com/Alfrex92/animers/tree/master/src/components/molecules/MemberInfo

**Comment by gojutin** [comment]
You are so close! Looks like you just need to add `/register` to the end of the `import "@storybook/addon-knobs` statement in `.storybook/addons.js`. 

So, the file should look like this:

```js
import "@storybook/addon-options/register"
import "@storybook/addon-actions/register"
import "@storybook/addon-viewport/register"
import "@storybook/addon-a11y/register"
import "@storybook/addon-knobs/register"
```

**Comment by Alfrex92** [comment]
Thanks a lot, I really appreciate it. It's working 😄
